### ISSUE TITLE
Issues deploying on vercel

### ISSUE THREAD

**Issue by diegoleft** [IlusionDev/nextjs-sitemap-generator#57]
Hello guys, I'm getting this issue when deploy on Vercel.
```

(node:1364) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/vercel/6448929c/.next/server/pages'
-- | --
at Object.readdirSync (fs.js:955:3)
at SiteMapper.buildPathMap (/vercel/6448929c/node_modules/nextjs-sitemap-generator/core.js:88:35)
at SiteMapper.getSitemapURLs (/vercel/6448929c/node_modules/nextjs-sitemap-generator/core.js:117:28)
at SiteMapper.sitemapMapper (/vercel/6448929c/node_modules/nextjs-sitemap-generator/core.js:150:33)
at module.exports (/vercel/6448929c/node_modules/nextjs-sitemap-generator/index.js:13:22)
at Object.<anonymous> (/vercel/6448929c/next.config.original.1600262120916.js:120:1)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
(node:1364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

My sitemap config:
```

sitemap({
  baseUrl: "https://www.mysite.com",
  pagesDirectory: __dirname + "/.next/server/pages",
  targetDirectory: "public/",
  ignoredExtensions: ["js", "map"],
  changefreq: "",
  priority: "", 
});

```
The issue is only on vercel, on my local is working great

**Comment by mxmzb** [comment]
@diegoleft I think you need to use 

```
pagesDirectory: __dirname + "/.next/serverless/pages",
```

for Vercels environment.

**Comment by JannikZed** [comment]
we get this error on vercel: 
```
(node:2017) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/vercel/workpath0/.next/serverless/pages'
```
